services:
  database:
    container_name: ${MONGO_CONTAINER_NAME}
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    command: mongod --quiet --logpath /dev/null
    ports:
      - ${MONGO_INITDB_PORT}:${MONGO_INITDB_PORT}
    volumes:
      - dsgo-database:/data/db
    restart: ${MONGO_RESTART}
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin -u ${MONGO_INITDB_ROOT_USERNAME} -p ${MONGO_INITDB_ROOT_PASSWORD} --quiet | grep 1
      interval: 12s
      timeout: 12s
      retries: 12

  server:
    container_name: ${SERVER_CONTAINER_NAME}
    image: ${SERVER_IMAGE_TAG}
    build:
      context: ..
      dockerfile: deployments/Dockerfile
      target: ${SERVER_BUILD_TARGET}
    environment:
      DATABASE_URI: "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@database:${MONGO_INITDB_PORT}"
      ALLOWED_HOSTS: ${SERVER_ALLOWED_HOSTS}
      URL: ${SERVER_URL}
      GIN_MODE: ${SERVER_MODE}
      PORT: ${SERVER_PORT}
    command: ${SERVER_COMMAND}
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${SERVER_PROXY_PORT}:${SERVER_PROXY_PORT}
    volumes:
      - ${SERVER_VOLUMES_APP}
      - dsgo-modules:/go/pkg/mod
    restart: ${SERVER_RESTART}
    depends_on:
      database:
        condition: service_healthy

volumes:
  dsgo-database:
    name: ${DATABASE_VOLUME}
  dsgo-server:
    name: dsgo-server
  dsgo-modules:
    name: dsgo-modules
