services:
  database-mysql:
    container_name: ${DATABASE_MYSQL_CONTAINER_NAME}
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_MYSQL_NAME}
      MYSQL_USER: ${DATABASE_MYSQL_USERNAME}
      MYSQL_PASSWORD: ${DATABASE_MYSQL_PASSWORD}
    ports:
      - ${DATABASE_MYSQL_PORT}:${DATABASE_MYSQL_PORT}
    volumes:
      - database-mysql:/var/lib/mysql
    restart: ${DATABASE_MYSQL_CONTAINER_RESTART}
    healthcheck:
      test: mysqladmin ping -h database-mysql --silent
      interval: 12s
      timeout: 12s
      retries: 12

  dsgo:
    container_name: ${DSGO_CONTAINER_NAME}
    image: ${DSGO_IMAGE_TAG}
    build:
      context: ..
      dockerfile: deployments/Dockerfile
      target: ${DSGO_IMAGE_BUILD_TARGET}
    environment:
      DATABASE_MYSQL_DSN: "${DATABASE_MYSQL_USERNAME}:${DATABASE_MYSQL_PASSWORD}@tcp(database-mysql:${DATABASE_MYSQL_PORT})"
      DATABASE_MYSQL_NAME: ${DATABASE_MYSQL_NAME}
      DATABASE_SQLITE_NAME: ${DATABASE_SQLITE_NAME}
      DSGO_SERVER_GIN_URL: "${DSGO_SERVER_GIN_URL}:${DSGO_SERVER_GIN_PORT}"
      DSGO_SERVER_GIN_PORT: ${DSGO_SERVER_GIN_PORT}
      DSGO_SERVER_GIN_MODE: ${DSGO_SERVER_GIN_MODE}
      DSGO_SERVER_GIN_ALLOWED_HOSTS: ${DSGO_SERVER_GIN_ALLOWED_HOSTS}
      DSGO_BOT_DISCORD_APP_ID: ${DSGO_BOT_DISCORD_APP_ID}
      DSGO_BOT_DISCORD_APP_PUBLIC_KEY: ${DSGO_BOT_DISCORD_APP_PUBLIC_KEY}
      DSGO_BOT_DISCORD_APP_TOKEN: ${DSGO_BOT_DISCORD_APP_TOKEN}
      DSGO_BOT_DISCORD_TEST_GUILD_ID: ${DSGO_BOT_DISCORD_TEST_GUILD_ID}
      DSGO_DEV_AIR_PROXY_PORT: ${DSGO_DEV_AIR_PROXY_PORT}
    command: ${DSGO_CONTAINER_START}
    ports:
      - ${DSGO_SERVER_GIN_PORT}:${DSGO_SERVER_GIN_PORT}
      - ${DSGO_DEV_AIR_PROXY_PORT}:${DSGO_DEV_AIR_PROXY_PORT}
    volumes:
      - ${DSGO_CONTAINER_VOLUME}
      - dsgo-modules:/go/pkg/mod
    restart: ${DSGO_CONTAINER_RESTART}
    depends_on:
      database-mysql:
        condition: service_healthy

volumes:
  database-mysql:
    name: ${DATABASE_MYSQL_CONTAINER_VOLUME}
  dsgo-logs:
    name: dsgo-logs
  dsgo-modules:
    name: dsgo-modules
