// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.707
package fomantic

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Init() templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_Init_3d8c`,
		Function: `function __templ_Init_3d8c(){$.api.settings.api = {
        "create user" : "/",
        "read user" : "/",
        "update user" : "/",
        "delete user" : "/",
    };
    
    $.api.settings.serializeForm = true;

    $.api.settings.contentType = "application/json; charset=UTF-8";

    $.api.settings.beforeSend = function(settings) {
        settings.data = JSON.stringify(settings.data);
        return settings;
    };

    $.api.settings.successTest = function(response) {
        if(response && response.success) {
            return response.success;
        }

        return false;
    };
}`,
		Call:       templ.SafeScript(`__templ_Init_3d8c`),
		CallInline: templ.SafeScriptInline(`__templ_Init_3d8c`),
	}
}

func Fomantic() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
